---
name: Build QMK firmware
'on': [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keymap:
          - og60
    steps:
      - name: checkout qmk_firmware
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive

      - name: checkout userspace
        uses: actions/checkout@v3
        with:
          path: users/${{ github.actor }}

      - name: build firmware
        run: qmk compile "users/${{ github.actor }}/${{ matrix.keymap }}.json"

      - name: archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: "${{ github.actor }}_${{ matrix.keymap }}"
          path: |
            *.hex
            *.bin
            *.uf2
