---
name: Build QMK firmware
'on': [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keymap:
          - og60
          - planck_rev7_ortho_4x12
    steps:
      - name: Set up QMK build environment
        run: qmk setup --yes --branch ${{ github.repository_owner }} ${{ github.repository_owner }}/qmk_firmware

      - name: build firmware
        run: qmk compile "users/${{ github.repository_owner }}/${{ matrix.keymap }}.json"

      - name: archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: "${{ github.repository_owner }}_${{ matrix.keymap }}"
          path: "/qmk_firmware/.build/${{ matrix.keymap }}.{hex,bin,uf2}"
          if-no-files-found: error
